import { Component, OnInit } from '@angular/core';
import { Content } from '../helper-files/content-interface';
import { HobbiesService } from '../service/hobbies-service.service';
import { MessageServiceService } from '../service/message-service.service';

@Component({
  selector: 'app-content-list',
  templateUrl: './content-list.component.html',
  styleUrls: ['./content-list.component.scss']
})
export class ContentListComponent implements OnInit {
  content:Content[]=[];
  ngOnInit(): void {
    this.gethobbies();
  }
  gethobbies()
  {
    this.contentService.getContent().subscribe(content => {
      this.content = content;
      this.messageService.addMessage('Content array loaded!');
      console.log(this.content)
    });
  }
  onContentAdded(newContent: Content) {
    debugger
    this.contentService.addcontent(newContent).subscribe(con=>{
      this.gethobbies();
      this.messageService.addMessage('new content has been added');
    });
    // this.contentService.addContent(newContent)
    //   .subscribe(content => {
    //     // set the new id generated by the server
    //     newContent.id = content.id;
    //     // add the new content to the array
    //     this.contents.push(newContent);
    //   });
  }
  constructor(private contentService: HobbiesService,private messageService: MessageServiceService)
  {
    
  }
  searchTitle:string | undefined;
  exist=false;
  message:string | undefined
  search()
  {
   const contentSearch= this.content.find(search=>search.title.toLowerCase()==this.searchTitle?.toLowerCase());
   this.exist=!!contentSearch;
   this.message=this.exist? `Content with tilte "${this.searchTitle}"  exist`: `Content with tilte "${this.searchTitle}"  does not exist`
  }


 




}